### ISSUE TITLE
Renaming <variant> to into_<variant>?

### ISSUE THREAD

**Issue by youknowone** [kdy1/is-macro#12]
is-macro generates `as_` methods by naming convention https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv

But `into_` is actually named as its variant itself. Though it will be breaking change, is there any chance to consider renaming?

Minimal backward compatibility still will be kept by adding `#[deprecation]` to previous methods.

**Comment by kdy1** [comment]
Those methods do not have `into_` prefix because of [`Result::ok`](https://doc.rust-lang.org/std/result/enum.Result.html#method.ok)

**Comment by kdy1** [comment]
A type in the standard library does not use `into_` as a prefix, and the operation seems identical to me. (E -> `Option<T>`)

**Comment by youknowone** [comment]
Thank you. I also realized `Result::ok` returns `Option<T>` while `into_something` mostly just returns T
