### ISSUE TITLE
Attribute to rename generated method names

### ISSUE THREAD

**Issue by snejugal** [kdy1/is-macro#4]
While we're adopting `is-macro` in `tbot`, we found that translation to `snake_case` may yield a bit unexpected results around digits. For this enum, I would expect that the generated `is_` method would be named `is_video_mp4`, not `is_video_mp_4` (notice the underscore before the number):

```rust
#[derive(Is)]
pub enum MimeType {
    …
    /// The `video/mp4` MIME type.
    VideoMp4,
}
```

Such cases should probably be left to humans, because one might actually expect an underscore inserted between a word and a digit. I suggest an attribute, setting which changes the generated method names:

```rust
#[derive(Is)]
pub enum MimeType {
    …
    #[is(root = "video_mp4")]
    VideoMp4,
}
```

With this attribute, `Is` would generate `is_video_mp4` instead of `is_video_mp_4`. If it were possible for this variant, it would also emit `expect_video_mp4` and `video_mp4` instead of `expect_video_mp_4` and `video_mp_4`. This can be extended in the future with ability to choose names for each method or change their prefixes. The only downside to this is a more complicated implementation. Also, if this is going to be implemented, we should probably come up with a better name than `root`.

(by the way, we really appreciate this crate for generating `expect_` and taking methods, and also that we don't have to manually implement `is_` methods 😀)

**Comment by kdy1** [comment]
I fixed it and published `is-macro@v0.1.4`.
You can rename the variant like `is(name = "video_mp4")`

cc @SnejUgal
